// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-DijfrhyUZ7SKeJ-Bf5FF4OCq79ca8Q',
    appId: '1:606735193701:web:4d0bb612caef8b1aa8588c',
    messagingSenderId: '606735193701',
    projectId: 'reddit-d3391',
    authDomain: 'reddit-d3391.firebaseapp.com',
    storageBucket: 'reddit-d3391.appspot.com',
    measurementId: 'G-100QX60NPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK1zzZrmWTxeREEaTKTNPPNvUke-mzYFU',
    appId: '1:606735193701:android:856f7f41164bafb3a8588c',
    messagingSenderId: '606735193701',
    projectId: 'reddit-d3391',
    storageBucket: 'reddit-d3391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCrczIpLqS5W0g7aj5osnoquBFIEZt58Q',
    appId: '1:606735193701:ios:4a6f633f51c5c122a8588c',
    messagingSenderId: '606735193701',
    projectId: 'reddit-d3391',
    storageBucket: 'reddit-d3391.appspot.com',
    iosClientId: '606735193701-o9l96l7qu6n87mnqi5esk482vnbfug9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCrczIpLqS5W0g7aj5osnoquBFIEZt58Q',
    appId: '1:606735193701:ios:4a6f633f51c5c122a8588c',
    messagingSenderId: '606735193701',
    projectId: 'reddit-d3391',
    storageBucket: 'reddit-d3391.appspot.com',
    iosClientId: '606735193701-o9l96l7qu6n87mnqi5esk482vnbfug9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
